### ISSUE TITLE
Regex does not parse sample names correctly

### ISSUE THREAD

**Issue by vitu1** [nf-core/demultiplex#105]
### Description of the bug

Having a SampleSheet.csv that contains Sample_IDs with characters that partly matches the [Undetermined] regex will cause those files to not be recognized as outputs of the BCLCONVERT process

Steps to reproduce:
Edit the SampleSheet.csv that comes with the test dataset by changing the Sample_ID to something like 'Sample-Unspiked'

Example SampleSheet.csv:
[Header]

[Reads]
110

[Settings]

[Data]
Sample_ID,Sample_Name,Description,Sample_Project
Sample-Unspiked,Sample-Unspiked,,

Running the nf-core/demultiplex test with this SampleSheet.csv will cause the error:
Missing output file(s) `**[!Undetermined]_S*_R?_00?.fastq.gz` expected by process `NFCORE_DEMULTIPLEX:DEMULTIPLEX:BCL_DEMULTIPLEX:BCLCONVERT (220422_M11111_0222_000000000-K9H97.1)`

**Comment by matthdsm** [comment]
Hi @vitu1 

Thanks for reporting this. Do you have a suggestion how we could make it better? This is a simple glob mind you, not a full regex.

Thanks
M

**Comment by Aratz** [comment]
This should be fixed on `dev` now, see https://github.com/nf-core/modules/pull/3796 and https://github.com/nf-core/demultiplex/pull/141 for details.
