### ISSUE TITLE
Add samplesheet generation

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/demultiplex#149]
After running demultiplex it'll make a samplesheet for rnaseq and other pipelines.

We can pull the functionality out of fetchngs, and make it a subworkflow and use the logic here as well.

```[tasklist]
### Tasks
- [ ] Create a subworkflow with fetchngs samplesheet generation
- [ ] Integrate it in demultiplex
```

**Comment by apeltzer** [comment]
Added in #236
