### ISSUE TITLE
Falco result for single End FastQ cannot show in the MultiQC report 

### ISSUE THREAD

**Issue by wzheng0520** [nf-core/demultiplex#169]
### Description of the bug

Looks like when we use the pipeline for single end samples, the multiQC report cannot have the result from `FALCO` (named as FASTQC section in multiQC report). I checked the code and find it might cause by `multiqc_config.yml`. It give is following code `fastqc/data: fn: "*_fastqc_data.txt" `. However, for the single end fastq, the FALCO generated results end with `_data.txt` rather than `_fastqc_data.txt` .

**Comment by Aratz** [comment]
@wzheng0520 I've fixed Falco's output in the modules repository, the update will be included in this pipeline soon. Meanwhile, you should be able to use it if you run `nf-core module update` locally.
