### ISSUE TITLE
Issue with AWS and NfcoreTemplate.groovy

### ISSUE THREAD

**Issue by rulixxx** [nf-core/demultiplex#171]
### Description of the bug

Seems like the File methods in NfcoreTemplate.groovy don't like s3: locations. I had to change them to use Nextflow's file method. I think that nf-core would have fixed this already so probably just have to update this file to a more recent version to fix things.

**Comment by k1sauce** [comment]
I assume this is fixed by #186 as well, since the latest template does not use NfcoreTemplate.groovy
