### ISSUE TITLE
URGENT: pin nf-validation version

### ISSUE THREAD

**Issue by nvnieuwk** [nf-core/demultiplex#175]
### Description of the bug

To prevent breaking this pipeline in the near future, the nf-validation version should be pinned to version 1.1.3 like:

```
plugins {
    id 'nf-validation@1.1.3'
}
```

**Comment by Aratz** [comment]
Isn't this the case already (on `dev`)? :thinking: 
https://github.com/nf-core/demultiplex/blob/de8795836e49d700f53e5890b911cd963a80154b/nextflow.config#L193-L195

**Comment by nvnieuwk** [comment]
Perfect! Any idea on when the next release will be?

**Comment by Aratz** [comment]
This has not been discussed yet, but since it has only be template updates since the last release I guess it should be quite straight forward. I can take a look next week :+1:
