### ISSUE TITLE
Reads dropped when demultiplexing a sample across lanes. 

### ISSUE THREAD

**Issue by AaronNHart** [nf-core/demultiplex#182]
### Description of the bug

First off, thank you for maintaining this pipeline, it looks very useful!

While informally validating the pipeline on an old study, I believe I observed that fastq files from the same sample but run from different lanes overwrite one another due to being written to the same location for each lane. 

My scenario is similar to the usage documentation with a samplesheet like:

id,samplesheet,lane,flowcell
foo,s3://SampleSheet.csv,1,s3://foo/
foo,s3://SampleSheet.csv,2,s3://foo/

### Command used and terminal output

```console
nextflow run nf-core/demultiplex/dev/ \
   -config ./my.config \
   --input samplesheet.csv \
   --demultiplexer bclconvert \
   --outdir s3://bucket/out/ \
   -work-dir s3://bucket/work/
```

### Relevant files

You can see here that the file shown is shortly overwritten, the timing corresponds to the moment when each bclconvert jobs completes.  

![image](https://github.com/nf-core/demultiplex/assets/4049935/3d62bc4f-b67a-4cb0-ab83-48a23b5dd59c)

I prefer to not directly post the whole log file, but if you have questions about it I can pull out some details as needed. 

### System information

* Nextflow 23.10.1 build 5891
* nf-core/demultiplex 1.4.1
* head job from my desktop (Ubuntu 22)
* AWS Batch executor (w/docker)

**Comment by nschcolnicov** [comment]
Hi @AaronNHart, this PR should have addressed the issue: https://github.com/nf-core/demultiplex/pull/225
I know it has been a long time since you reported this, but if you are still needing to execute the pipeline, could you please retry your execution using the latest version of dev?

**Comment by AaronNHart** [comment]
Thanks a lot for the follow up. In the mean time I've changed roles and no longer have access to this infrastructure but if I do pick up the pipeline again I'll be sure to check.
