### ISSUE TITLE
Include test of PE data

### ISSUE THREAD

**Issue by k1sauce** [nf-core/demultiplex#189]
### Description of feature

There is some logic around handling of PE and SE fastq files, would be nice to have a test for this as well.

**Comment by grst** [comment]
As discussed with @atrigila and @nschcolnicov fixing this would entail adding a test case to https://github.com/nf-core/demultiplex/tree/master/tests/pipeline that runs as part of the CI.

**Comment by nschcolnicov** [comment]
Addressing this issue in this PR: https://github.com/nf-core/demultiplex/pull/214
