### ISSUE TITLE
Add Support for 10X Single Cell Demux

### ISSUE THREAD

**Issue by apeltzer** [nf-core/demultiplex#195]
### Description of feature

The module for this exists already via cellranger mkfastq --> so should be a separate subworkflow that can handle 10X data.

**Comment by nschcolnicov** [comment]
-TODO:
Push test-dataset branch to nf-core/test-datasets once its done testing:
https://github.com/nschcolnicov/test-datasets/tree/demultiplex 
Push modules branch to nf-core/modules once its done testing: 
https://github.com/nschcolnicov/modules/tree/master
Push demultiplex branch to nf-core/demultiplex once its done testing: https://github.com/nschcolnicov/demultiplex/tree/add_demultiplexing_subworkflow_10x

**Comment by nschcolnicov** [comment]
Putting this one on hold until I fix the CI test https://github.com/nf-core/demultiplex/issues/211

**Comment by nschcolnicov** [comment]
All done
