### ISSUE TITLE
Containerise licence software

### ISSUE THREAD

**Issue by csawye01** [nf-core/demultiplex#2]
- bcl2fastq is recently not publicly available
- CellRanger requires email to access software

**Comment by TomKellyGenetics** [comment]
This is not strictly the case. Cell Ranger version 3.0.2 is available open source on at MIT License: https://github.com/10XGenomics/cellranger/blob/3.0.2/LICENSE

This is the version of Cell Ranger implemented in the Docker Container here: https://github.com/nf-core/demultiplex/pull/5
