### ISSUE TITLE
UMI handling for DEMUX pipeline

### ISSUE THREAD

**Issue by apeltzer** [nf-core/demultiplex#200]
Add UMI handling feature to demux pipeline that extracts the UMIs from input files and then adds the UMI to the respective fastq header.

**Comment by grst** [comment]
Does it make sense to have this in the demux workflow? Personally I'd rather keep manipulations to the fastq files minimal and leave it to downstream workflows to deal with UMIs and the like.

**Comment by apeltzer** [comment]
Fair enough, that issue was only raised via me but I tend to have the same opinion on this one too 👍🏻  Lets not do it and instead rather get downstream workflows to tackle this appropriately (rnaseq, sarek, smrnaseq can all do it).
