### ISSUE TITLE
Disable automated trimming by demultiplexing tools.

### ISSUE THREAD

**Issue by grst** [nf-core/demultiplex#207]
### Description of feature

When using an Illumina Samplesheet with `Adapters` specified in the `[Settings]` section, bcl2fastq, cellranger mkfastq or BCLconvert automatically perform adapter trimming, e.g. 

```
[Settings],,,,,,,,,,,
Adapter,AGATCGGAAGAGCACACGTCTGAACTCCAGTCA,,,,,,,,,,
AdapterRead2,AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT,,,,,,,,,,
```

I do not think we want to use this feature because
 * trimming is done in a separate step using `fastp` by default, which would result in double-trimming (fastp also reliably auto-detects the adapters, there is no need for storing the adapter sequences). 
 * trimming might result in issus with single-cell or UMI data. In fact 10x urgently recommends to disable trimming during demux:

![image](https://github.com/user-attachments/assets/c088c65c-cff3-48c8-95aa-6d74f289280e)

I therefore suggest to include a step that removes those lines from the input samplesheets, unless it is specifically disabled via a config flag. This can be achieved e.g. in groovy with a snippet such as

```groovy
 samplesheet_in
        .readLines()
        .each { line ->
            if ( line =~ /Adapter,[ACGT]+,/ ) {
                line = line.replaceAll(/Adapter,[ACGT]+,/, 'Adapter,,')
            }
            else if ( line =~ /AdapterRead2,[ACGT]+,/ ) {
                line = line.replaceAll(/AdapterRead2,[ACGT]+,/, 'AdapterRead2,,')
            }
            samplesheet_out << line + '\n'
        }
```

A section should be added to the documentation dedicated to trimming. 

CC @apeltzer

**Comment by nschcolnicov** [comment]
Putting this one on hold until https://github.com/nf-core/demultiplex/issues/209 is closed

**Comment by nschcolnicov** [comment]
PR for #209 was merged, closing this ticket.
