### ISSUE TITLE
Copy samplesheet into output directory

### ISSUE THREAD

**Issue by grst** [nf-core/demultiplex#215]
### Description of feature

I think it would be nice to include the demux samplesheet that is used as input for bcl2fastq, bclconvert etc. into the flowcell output folder for posteriority. The input samplesheet also often serves as a referece point for creating samplesheets for a downstream pipeline, e.g. rnaseq. 

CC @apeltzer

**Comment by apeltzer** [comment]
Agree 👍

**Comment by apeltzer** [comment]
Meant is the flowcell samplesheet, not the samplesheet for the pipeline itself 👍🏻
