### ISSUE TITLE
checkqc doesn't run for bclconvert

### ISSUE THREAD

**Issue by grst** [nf-core/demultiplex#226]
### Description of the bug

I'm running the exact same flowcell, once with bcl2fastq and once with bclconvert. 
CheckQC only runs when bcl2fastq is selected as demultiplexer. 

I'd expect checkQC to run in all cases (at least with Illumina's bcl2fastq/bclconvert, but I don't think there would be any reason not to run it with the other demultiplexers as well?)

CC @apeltzer 

### Relevant files

BCL2FASTQ
![image](https://github.com/user-attachments/assets/92e6eccb-be16-471c-bda1-20e28b4e09f6)

Bclconvert
![image](https://github.com/user-attachments/assets/d163c98d-6eb9-4849-aed9-be10046321bc)

**Comment by apeltzer** [comment]
IIRC; checkqc is not compatible with bclconvert output.

**Comment by apeltzer** [comment]
Not entirely sure this is (still?) valid, please try to set it up for bclconvert - if it doesnt work,

**Comment by grst** [comment]
Thanks for checking! Then I'll close this issue!
