### ISSUE TITLE
Make tests work again on release PR upon fixes in modules / utils subworkflows

### ISSUE THREAD

**Issue by apeltzer** [nf-core/demultiplex#243]
Unfortunately the tests don't work anymore. I suspect that it has to do something with this one here: https://github.com/nf-core/test-datasets/pull/1283

**Comment by nschcolnicov** [comment]
On it

**Comment by apeltzer** [comment]
Related PRs https://github.com/nf-core/tools/issues/3111
and https://github.com/nf-core/modules/issues/6166
