### ISSUE TITLE
Reached automation hook

### ISSUE THREAD

**Issue by apeltzer** [nf-core/demultiplex#262]
### Description of the bug

Once the pipeline finishes and some email is set, it will not finish sending it. Attached the logfile of whats going on in the background, doesnt matter if i keep the hook_url set or not / once I add email functionality / use the email feature, it hangs up until I cancel. 

![image](https://github.com/user-attachments/assets/ccf24d66-ca12-488e-a355-86836f1c53f3)

**Comment by apeltzer** [comment]
Could be something around emailing functionality and the way its generated (attaching multiqc report).

**Comment by apeltzer** [comment]
https://community.seqera.io/t/reached-automation-hook-nextflow-doesnt-move-on/

**Comment by grst** [comment]
Is this specific to the multiplex pipeline, or should this go into `tools`?

**Comment by apeltzer** [comment]
I am not sure, didnt try it with other pipelines

**Comment by apeltzer** [comment]
This is a bug that @robsyme now fixed - see slack conversation on this with help from @FelixKrueger  https://nfcore.slack.com/archives/CE5LG7WMB/p1732919344822769

**Comment by nschcolnicov** [comment]
@apeltzer Those changes alone listed in the commit you shared didn't fix the issue for me, I'll look into it

**Comment by nschcolnicov** [comment]
@apeltzer Nevermind it was my environment that was missing the mail command, PR is open for this: https://github.com/nf-core/demultiplex/pull/294, I need to update an nf-core subworkflow first
