### ISSUE TITLE
Simplify samshee module

### ISSUE THREAD

**Issue by grst** [nf-core/demultiplex#268]
### Description of feature

Sameshee now has a proper CLI implemented, see
https://github.com/lit-regensburg/samshee?tab=readme-ov-file#commandline-tool

With that, I think we should 
 * get rid of the custom python script
 * turn samshee into a `nf-core/modules` module.

**Comment by grst** [comment]
I think this is a bit higher priority now as I had a samplesheet that failed (and shouldn't) with samshee v0.1.12, but passes with v0.2.0. 

In particular, lines like
```
[Header]
Description,,,,,,,,
```

that have an empty value in col2 led to an error. 

So let's prioritize this and make a samshee v0.2.0 module please. 

@apeltzer @atrigila @nschcolnicov

**Comment by nschcolnicov** [comment]
Created a PR for this: @grst @atrigila https://github.com/nf-core/modules/pull/6749. Let me know what you think.

**Comment by grst** [comment]
It wasn't evident for me what's the default logic of the samshee CLI so I did some digging:

* When the output format of samshee is Illumina `v2`, it will always validate the samplesheet as Illumina V2 sheet, even when no `--schema` option is present. 
* Therefore, a V1 samplesheet will always fail unless `--output-format sectioned` is given. People with V1 samplesheets can either skip samshee altogether or specify this as a tool option. Either way, samshee doesn't properly validate V1 samplesheets except that the content is parseable since there is no suitable schema available until now). I think this is OK behavior as long as this is properly documented. 
* The samplesheet could have not data section and still be valid. If we want to catch that, we'd need to add `--schema '{"required": ["BCLConvert_Data"]}'`. We can discuss if we should enable certain rules in the pipeline by default, but the standard V2 samplesheet logic is probably already a good start.

**Comment by grst** [comment]
Closed via https://github.com/nf-core/demultiplex/pull/275
