### ISSUE TITLE
Improve samplesheet generation

### ISSUE THREAD

**Issue by grst** [nf-core/demultiplex#272]
### Description of feature

It's great that the pipeline can generate samplesheets for downstream pipelines automatically. 
I suggest the following improvements: 
 * always generate all types of samplesheets. It's computationally cheap, it saves one pipeline parameter, and sometimes the data can be used for multiple pipelines (e.g. rnafusion + rnaseq)
 * allow to explicitly set the strandedness for rnaseq samplesheets. It's currently always 'auto', but I'd like to set it explicitly to `reverse` for Illumina libraries. 

Something we could also discuss at some later point is to carry on information from the demux samplesheet to the generated samplesheets, e.g. additional columns from the `[Data]` section could be added to the generated samplesheets. 

@apeltzer @atrigila @nschcolnicov

**Comment by grst** [comment]
Another issue: the output paths are not correct. 

They currently are: 
```
s3://xxxxxxxxxxxxx-dev/demultiplex/241003_A01664_XXXXXXXXXXXXXXX/101_d_xxx_S1_L001/101_d_xxx_S1_L001_R1_001.fastq.gz
```

while it should be

```
s3://xxxxxxxxxxxxx-dev/demultiplex/241003_A01664_XXXXXXXXXXXXXXX/241003_A01664_XXXXXXXXXXXXXXX/101_d_xxx_S1_L001/101_d_xxx_S1_L001_R1_001.fastq.gz
```

The path until `s3://xxxxxxxxxxxxx-dev/demultiplex/241003_A01664_XXXXXXXXXXXXXXX` is the output folder specified by the user, so it's not taking into account the publishDir subdirectory.

**Comment by grst** [comment]
I just tested this with the dev version, and it seems the output paths are still incorrect as described in this comment: https://github.com/nf-core/demultiplex/issues/272#issuecomment-2399221675

**Comment by nschcolnicov** [comment]
@grst Ok, I'll take a look

**Comment by nschcolnicov** [comment]
PR merged, closing this ticket
