### ISSUE TITLE
Make it possible to not split per lane when using bcl2fastq or bcl-convert

### ISSUE THREAD

**Issue by lbeltrame** [nf-core/demultiplex#288]
### Description of feature

Some illumina flowcells (like in the Nextseq 550 and in the 2000) are divided in lanes, but they all use the same samples (unlike the larger instruments). Therefore having a series of FASTQ divided by lane with these instruments is not very useful. Ideally `demultplex` should allow (off by deault) to avoid splitting by lanes if possible.

**Comment by grst** [comment]
afaik this can be set in the illumina samplesheet: 

```
[BCLConvert_Settings]
NoLaneSplitting,true
```
