### ISSUE TITLE
Add Kraken2

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/demultiplex#36]
Not sure what was going on with this one before, maybe @csawye01 or @drpatelh can shed some light here.

**Comment by drpatelh** [comment]
It was to look for contamination in the reads in a quick and unbiased way across organisms.

**Comment by matthdsm** [comment]
I'm not really sure this in the scope of a demultiplexing workflow. Sounds to me like that's more like extensive input QC to be done before starting a wf.

**Comment by drpatelh** [comment]
Be awesome to have contamination detection built-in here though.

**Comment by matthdsm** [comment]
No problem, we can keep te issue around for the future
Will there be room on the refgenie server for a kraken database?

**Comment by matthdsm** [comment]
Also, does kraken support remote db's or does it have to be local? 
e.g., can it read it's files straight from S3 (for example) or does it have to stage the entire thing locally?

**Comment by apeltzer** [comment]
Hey @matthdsm -  I have a subworkflow already fleshed out that does allow even to subsample fastqs using seqtk (unbiased) to speed up the process and then runs kraken2 on it, creating a report that can be fed into MultiQC directly. We use this internally already, will contribute now to subworkflows in modules and then we can simply take it from there 👍🏻

**Comment by Aratz** [comment]
Hi!

We actually have a use case for this at our platform and would like to include @apeltzer 's subworkflow into nf-core/demultiplex.

Is that ok if we start working on this during the Hackathon?

**Comment by apeltzer** [comment]
This is now implemented via https://github.com/nf-core/demultiplex/pull/220 - will be part of 1.5.0 release
