### ISSUE TITLE
Upstream BCLConvert changes to nf-core/modules

### ISSUE THREAD

**Issue by Emiller88** [nf-core/demultiplex#37]
When we're happy with where it's at, no rush we can keep dog fooding it here.

Just a reminder before we release v1.0.0

**Comment by Emiller88** [comment]
Should be able to update tests to actually run and not just use stub runs as well!
https://github.com/nf-core/demultiplex/pull/29#issuecomment-1110313802

**Comment by matthdsm** [comment]
https://github.com/nf-core/modules/pull/1569

**Comment by matthdsm** [comment]
bclconvert was updated in modules
