### ISSUE TITLE
Handle different demultiplexers in the same workflow

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/demultiplex#40]
### Description of feature

Rather than `params.demultiplexer` maybe we can handle this just off the sample sheet, either by name of the run or by the presence of a `SampleSheet.csv` or a `RunManifest.csv` and maybe parsing them a bit to infer the type. I'm thinking the latter is going to be the most elegant.

**Comment by Emiller88** [comment]
Probably the easiest thing. We'll have to see what users want, but maybe we could add an optional/blank field that takes the args for the demultiplexer as well!

**Comment by Emiller88** [comment]
I realized we can probably set demultiplex settings on a run basis, using `withLabel` or maybe we can get a `withTag` selector

```nextflow
process {
    withTag: "example1" {
        ext.args: "--tiles 1A"
    }
}
```

**Comment by grst** [comment]
There haven't been any requests for this in two years and I don't think that the demultiplexer is an argument that you'd commonly want to set on a per-flowcell basis. Closing this for now.
