### ISSUE TITLE
Check Samplesheet expects files to be remote

### ISSUE THREAD

**Issue by Emiller88** [nf-core/demultiplex#43]
### Description of the bug

```
request.urlopen(row[self._samplesheet_col]).getcode() == 200
```
This pattern doesn't work because it breaks for users running on local files and not downloading them.

### Command used and terminal output

```console
Using this samplesheet 

flowcell,samplesheet,lane,run_dir
miseq,https://raw.githubusercontent.com/nf-core/test-datasets/demultiplex/testdata/MiSeq/SampleSheet.csv,1,https://github.com/nf-core/test-datasets/raw/demultiplex/testdata/MiSeq/220422_M11111_0222_000000000-K9H97.tar.gz
aviti,./sim-data/RunManifest.csv,1,./sim-data/

It broke when I was trying to use local files
```

**Comment by matthdsm** [comment]
That's weird, I'm currently using ( a subworkflow version of) the pipeline without any issues, with both remote and local samplesheets.

**Comment by matthdsm** [comment]
https://github.com/CenterForMedicalGeneticsGhent/nf-cmgg-preprocessing/blob/testing/subworkflows/local/demultiplex/main.nf
