### ISSUE TITLE
Generate MD5 hashes of FastQ files

### ISSUE THREAD

**Issue by berguner** [nf-core/demultiplex#46]
### Description of feature

Hi,

It would be nice if the pipeline could generate md5sum values of `.fastq.gz` files.

**Comment by matthdsm** [comment]
Should be fixed in the latest commit

**Comment by berguner** [comment]
Thanks for the quick fix @matthdsm . I tested the latest commit and it worked well. However, the `.md5` files are saved under a `md5sum` folder instead of the flowcell folder. This might cause conflict for samples scattered into multiple flowcells similarly to issue addressed in commit 44879e13cc5e6f81fae0b052e6272e2f798f4862 .

**Comment by matthdsm** [comment]
Yes, I'm aware of that.
The issue here is that the the fastq has no more flowcell data attached in meta, so I'm not able to stage the data correctly.
I'll have to look into fixing that.

**Comment by matthdsm** [comment]
Should be fixed in the latest commit, along with fastp and fastqc
