### ISSUE TITLE
The process stop or cannot find correct file path when add NoLaneSplitting, true 

### ISSUE THREAD

**Issue by wzheng0520** [nf-core/demultiplex#80]
### Description of the bug

 I  add `NoLaneSplitting, true ` command in samplesheet to merge the Lane 1 and Lane 2. However, after I add this command, the BCLCONVERT demultiplexing show the file or path could not be found. I think it caused by `Missing output file(s) **[!Undetermined]_S*_L00?_R?_00?.fastq.gz expected by process`. But, the Undetermined reads are actually on there, but the sample I generated the full name is `Undetermined_S0_R2_001.fastq.gz`. I think there is no `L00?` in the name because I merged the lane together. 

This error are not only for the undetermined reads, when you try to merge the lane together, all the output file will be generated with name **_S*_00?_R?_00?.fastq.gz or **_S*_00?_I?_00?.fastq.gz. Therefore, I think if it is possible to add or make change on the globs to fix this issue in order to make sure when the people use the `NoLaneSplitting, true ` command, the process could work well?

**Comment by matthdsm** [comment]
should work
`**[!Undetermined]_S*@(_L00?_R?|_R?)_00?.fastq.gz`
and
`**Undetermined_S0@(_L00?_R?|_R?)_00?.fastq.gz`

**Comment by matthdsm** [comment]
https://github.com/nf-core/modules/pull/2745

**Comment by Emiller88** [comment]
Closed by https://github.com/nf-core/modules/pull/2745
