### ISSUE TITLE
bcl2fastq installation error

### ISSUE THREAD

**Issue by ushnaahmad** [nf-core/demultiplex#97]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The bcl2fastq module is not correctly installed in the docker image. When we run the demultiplex nf-core pipeline with any dataset, including the bcl2fast test profile, we see this warning in the .command.err file:

```
I/O warning : failed to load external entity "/usr/local/share/xsl/demux/GenerateReport.xsl"
  error
  xsltParseStylesheetFile : cannot parse /usr/local/share/xsl/demux/GenerateReport.xsl
  2023-02-02 18:28:14 [1743880] WARNING: Could not compute and write statistics for this conversion: libxslt failure
  2023-02-02 18:28:14 [1743880] Processing completed with 0 errors and 1 warnings.

```
Because of this error, bcl2fastq isn't able to generate any reports, and the Reports directory is empty. When we run the pipeline with S3 in the backend, Nextflow tries to upload the output on S3 but since the Reports directory is empty it gets confused and throws another error that breaks the pipeline.

```
Error executing process > 'NFCORE_DEMULTIPLEX:DEMULTIPLEX:BCL_DEMULTIPLEX:BCL2FASTQ (220422_M11111_0222_000000000-K9H97.1)'

Caused by:
  Missing output file(s) `Reports` expected by process `NFCORE_DEMULTIPLEX:DEMULTIPLEX:BCL_DEMULTIPLEX:BCL2FASTQ (220422_M11111_0222_000000000-K9H97.1)`

```
It looks like only the executable for bcl2fastq is extracted from the rmp, and the rest of the package is not fully installed: https://github.com/nf-core/demultiplex/tree/master/modules/nf-core/bcl2fastq and https://github.com/nf-core/modules/tree/master/modules/nf-core/bcl2fastq

### Command used and terminal output

```console
nextflow run 'https://github.com/nf-core/demultiplex' \
		 -name berserk_engelbart \
		 -params-file 'https://dev-nf-tower.tesseratx.internal/api/ephemeral/32X5Sn6bbRn7gWdllRq-0g.json' \
		 -with-tower 'https://dev-nf-tower.tesseratx.internal/api' \
		 -profile docker,test_bcl2fastq
```
These are the params:

```
params {
   input = 's3://fvl58-dev-pipelines-execution-data/inputs/nf-demux/flowcell_input.csv'
   demultiplexer = 'bcl2fastq'
   trim_fastq = true
   skip_tools = []
   multiqc_config = null
   multiqc_title = null
   multiqc_logo = null
   max_multiqc_email_size = '25.MB'
   multiqc_methods_description = null
   outdir = 's3://fvl58-dev-pipelines-execution-data/results/nf-demux/nf_tests'
   custom_config_version = 'master'
   custom_config_base = 'https://raw.githubusercontent.com/nf-core/configs/master'
   max_cpus = 16
   max_memory = '128.GB'
   max_time = '240.h'
   help = false
   publish_dir_mode = 'copy'
   plaintext_email = false
   monochrome_logs = false
   tracedir = '${params.outdir}/pipeline_info'
   validate_params = true
   show_hidden_params = false
   enable_conda = false
   email = null
   email_on_fail = null
   hook_url = null
   version = false
   schema_ignore_params = 'genomes'
   config_profile_description = 'Minimal test dataset to check pipeline function with bcl2fastq'
   config_profile_contact = null
   config_profile_url = null
   config_profile_name = 'Test bcl2fastq profile'
}

```

### System information

System information
Nextflow version: 22.10.1
Hardware: Nextflow Tower
Executor: awsbatch
Container: Docker

**Comment by maxulysse** [comment]
@nvnieuwk issue transfered

**Comment by nvnieuwk** [comment]
Thanks! I didn't know this was possible 🥳

**Comment by matthdsm** [comment]
Actually, this IS related to #modules, so I opened another related issue there.

**Comment by matthdsm** [comment]
@ushnaahmad, we would happily accept a pull request with an updated Dockerfile!

**Comment by matthdsm** [comment]
Fixed in https://github.com/nf-core/modules/pull/2897

**Comment by matthdsm** [comment]
@ushnaahmad,  we pushed a new image to docker hub. Can you pull that one and confirm it's working for you now?

`docker pull nfcore/bcl2fastq:2.20.0.422`

**Comment by matthdsm** [comment]
Whatever it is, it should be fixed now!

**Comment by Emiller88** [comment]
Closing it @ushnaahmad feel free to reopen if you still have the error!
